name: flumy_environment

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - numpy
  - matplotlib
  - scipy
  - joblib
  - pyqt
  - h5py
  - ipywidgets
  - pip
  - pip:
      - flumy
      - pyvista[all]  # Installing via pip with all optional dependencies
      - itkwidgets    # Excellent for volumetric grid inspection
      - trame         # Required for PyVista remote rendering