import os
import time
from joblib import Parallel, delayed
from flumy_worker import run_flumy_worker

# Main execution script for flumy simulations. The scripts sets up the parameters, directories, and parallel execution for generating multiple flumy samples. 
# Each sample is generated by calling the run_flumy_worker function with the specified parameters. 
# The results are collected and a summary of the generation process is printed at the end.

def os_check():
    """"
    Checks the operating system and sets the appropriate paths for the Flumy executable and base data directory.
    Returns:
        tuple: (flumy_exe_dir, base_path) where:
            - flumy_exe_dir (str): Path to the Flumy executable based on the operating system.
            - base_path (str): Base directory for data storage based on the operating system.
    """

    FLUMY_EXE_DIR_WINDWOWS = r"C:\Users\mathi\Downloads\flumy_8.501_win64\bin"          # Specify the path to the Flumy excecutable on Windows & Linux (Personalized to setup)

    if os.name == 'nt':  # Windows
        FLUMY_EXE_DIR = FLUMY_EXE_DIR_WINDWOWS
        BASE_PATH = os.path.join(os.getcwd(),'datasets','testing')

    else:  # Linux
        FLUMY_EXE_DIR = "/home/nfs/mtorresruhe/software/flumy/bin"
        # This uses the symlink in your home dir automatically
        home_dir = os.path.expanduser("~") 
        BASE_PATH = os.path.join(home_dir, 'data', 'datasets','training_dataset_upper_plain_delta_128')

    return FLUMY_EXE_DIR, BASE_PATH

def main(output_dir= "testing_dataset_upper_plain_delta_128_2", test_dir= "test_temp", 
         num_samples=10000, start_count=10000, base_seed=0, use_parallel=True, 
         n_jobs=16, save_format='npy', save_all_data=False):
    
    # adjust n_jobs if num_samples < n_jobs to avoid overhead
    if num_samples < n_jobs:
        n_jobs = num_samples
        print(f"Adjusted n_jobs to {n_jobs} since num_samples is only {num_samples}.")
    
    # --- Configureation ---
    FLUMY_EXE_DIR, BASE_PATH = os_check()
    OUTPUT_DIR = os.path.join(BASE_PATH, output_dir)
    TEMP_DIR = os.path.join(BASE_PATH, test_dir)

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    os.makedirs(TEMP_DIR, exist_ok=True)
    
    # --- Specify Flumy parameters ---
    FLUMY_PARAMS = {
        'F2G_DZ': 1,
        'DOMAIN_NX': 128,
        'DOMAIN_NY': 128,
        'DOMAIN_DX': 20,
        'DOMAIN_DY': 20,
        'ZUL_TOPO': 42,
        'DOMAIN_SLOPE':0.001,
        'ZUL_TYPE': 1,
        'EROD_COEF':8e-8,

        'CHNL_MARGIN': 5,               # This value indidicates how many channel widths away from the boundary the flumy excecutable has to generate the simulation -> this ensures  higher variation
        'CHNL_WIDTH': 100,              # Channel width
        'CHNL_MAX_DEPTH': 6,            # Deeper channel for a certain width leads to higehr NTG
        'CHNL_WAVELENGTH': 800,            # Higher wavelength for a certain width seems to lead to lower SI index
        'CHNL_SCALE_LOGNORM_MEAN': 100,        # This is the mean of the lognormal distribution for channel scaling. Higher values lead to wider channels.
        'CHNL_SCALE_LOGNORM_STDEV': 10,         # This is the standard deviation of the lognormal distribution for channel scaling. Higher values lead to more variability in channel widths.

        'AV_REG_FREQ': 2,
        'AV_REG_POISSON': 1000,
        'AV_LOC_FREQ': 2,
        'AV_LOC_POISSON': 600,
        'AV_LV_OB': 1,
        'AV_LOC_PROB1':0.3,
        'AV_LOC_PROB2':0.5,

        'AG_TYPE': 2,
        'AG_OB_FREQ': 2,
        'AG_OB_POISSON': 45,
        'AG_OB_DIST': 3,
        'AG_OB_LOGNORM_MEAN': 0.07,
        'AG_OB_LOGNORM_STDEV': 0.007,
        'AG_OB_PEAT': 20,
        'LAUNCH_IT': -1
    }

    ### --- Script excecution ---
    sample_ids = list(range(start_count, start_count + num_samples))
    print(f"Starting batch of {num_samples} samples.")
    print(f"Parallel: {use_parallel} | Format: .{save_format}")

    start_time = time.time()

    if use_parallel:
        results = Parallel(n_jobs=n_jobs)(
            delayed(run_flumy_worker)(
                sim_id=sid,
                base_seed=base_seed,
                flumy_exe_dir=FLUMY_EXE_DIR,
                output_dir=OUTPUT_DIR,
                temp_dir=TEMP_DIR,
                save_format=save_format,
                save_all_data=save_all_data,
                **FLUMY_PARAMS
            ) for sid in sample_ids
        )
    else:
        results = []
        for sid in sample_ids:
            res = run_flumy_worker(
                sim_id=sid,
                base_seed=base_seed,
                flumy_exe_dir=FLUMY_EXE_DIR,
                output_dir=OUTPUT_DIR,
                temp_dir=TEMP_DIR,
                save_format=save_format,
                save_all_data=save_all_data,
                **FLUMY_PARAMS
            )
            results.append(res)
            
    end_time = time.time()
    success_count = sum(1 for r in results if r)
    
    print("\n" + "="*40)
    print("BATCH GENERATION COMPLETE")
    print("="*40)
    print(f"Successfully generated: {success_count}/{num_samples} samples.")
    print(f"Total time taken: {(end_time - start_time)/60:.2f} minutes.")

if __name__ == "__main__":
    print("Starting Flumy sample generation (iteration 1)")
    main()